config/routes.rb
#config/routes.rb
Rails.application.routes.draw do |map|
  resources :messages, :controller => 'moonshado/messages', :only => [:index, :show, :new, :create, :destroy] do
		member do
			post 'receive'
			post 'report'
		end
  end
end

app/models/message.rb
# @m = Message.new(:to => '12602498980', :body => "Body of a Message")
class Message < ActiveRecord::Base
  
  validates_length_of :body, :in => 1..160
  validates_format_of :to, :with => /(1\d{10}|\+\d{11,}|\d{5})/
  
  scope :inbound, where(:to => Moonshado::SMS_API_CONFIG[:short_code])
  scope :outbound, where(:from => Moonshado::SMS_API_CONFIG[:short_code])
  scope :read, where('read_at is not null')
  scope :unread, where(:read_at => nil)
  
  def deliver!
    resp = Moonshado::Base.deliver(self)
    if resp == 10
      self.update_attributes(:response_code => 10, :sent_at => DateTime.now)
    else
      self.update_attributes(:response_code => resp)
    end
  end
  
  def inbound?
    to == Moonshado::SMS_API_CONFIG[:short_code]
  end
  
  def outbound?
    from == Moonshado::SMS_API_CONFIG[:short_code]
  end
  
  def read?
    read_at.nil?
  end
  
  def device_address
    inbound? ? from : to
  end
  
  def message_class
    "message #{ read? ? 'unread' : 'read' }"
  end
  
  def response
    Moonshado::RESPONSE_CODES[response_code.to_s]
  end
  
  def status_object
    Moonshado::STATUS_CODES[status_code.to_s]
  end
  
  def status
    status_object.name unless status_object.nil?
  end
  
  def status_detail
    status_object.detail unless status_object.nil?
  end
  
  def get_status
  end
  
end

app/controllers/messages_controller.rb
  class MessagesController < ApplicationController
    
    unloadable
  
    before_filter :get_message, :only => [:show, :delete]
    before_filter :check_hash, :only => [ :report, :receive ]
  
    def index
      @inbound = Message.inbound.unread
      @outbound = Message.outbound
      render :template => "/moonshado/messages/index"
    end
  
    def new
      @message = Message.new
      render :template => "/moonshado/messages/new"
    end
  
    def create
      @message = Message.new(params[:message].merge({:from => Moonshado::SMS_API_CONFIG[:short_code]}))
      result = @message.save && @message.deliver! ? "Message sent." : "Message could not be sent."
      redirect_to message_path(@message.id), :notice => result
    end
  
    def show
      render :template => "/moonshado/messages/show"
    end
  
    def delete
      @message.destroy
      redirect_to messages_path, :notice => "Message deleted."
    end
    
    # carrier, device_address, message_subid - starting with 0, status_code, status_info, update_date, country
    def report
    end

    def receive
      @message = Message.new(
        :carrier      => params[:carrier],
        :from         => params[:device_address],
        :to           => params[:inbound_address],
        :country      => params[:country],
        :body         => params[:message],
        :timestamp    => params[:timestamp]
      )
      if @message.save
        head :created, :location => message_path(@message)
      end
    end
  
    private
  
    def get_message
      if params[:id]
        @message = Message.find(params[:id])
      end
      if @message.nil?
        redirect_to 'index'
      end
    end
    
    def check_hash
      params[:hash] == Moonshado::Base.client_hash
    end
  
  end

app/views/moonshado/messages/_message.html.erb
<div class="<%= message.message_class %>" id="message_<%= message.id %>">
	<strong><%= message.to %></strong> -- <%= message.body %><br>
	<em><%= message.from %> at <%= message.sent_at %></em>
</div>

app/views/moonshado/messages/index.html.erb
<h2>Inbound Messages</h2>
<%= render :partial => '/moonshado/messages/message', :collection => @inbound %>

<h2>Outbound Messages</h2>
<%= render :partial => '/moonshado/messages/message', :collection => @outbound %>

<%= link_to "Send Message", new_message_path %>

app/views/moonshado/messages/new.html.erb
<% form_for @message do |f| -%>
  <p>
		<%= f.label :to, "To" %><br>
		<%= f.text_field :to 	%>
	</p>
	<p>
		<%= f.label :body, "Message" %><br>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.submit "Send", :disable_with => 'Sending...' %>
	</p>
<% end -%>

app/views/moonshado/messages/show.html.erb
<p><strong>To:</strong><br>
<%= @message.to %></p>

<p><strong>From:</strong><br>
<%= @message.from %></p>

<p><strong>Message:</strong><br>
<%= @message.body %></p>

<p><strong>Sent at:</strong><br>
<%= @message.sent_at %></p>


<pre>
Response Code: <%= @message.response_code %>
Response: <%= @message.response %>
Status Code: <%= @message.status_code %>
Status: <%= @message.status %>
Status Detail: <%= @message.status_detail %>
Carrier: <%= @message.carrier %>
Short Code: <%= @message.shortcode %>
Parent ID: <%= @message.parent_id %>
Country: <%= @message.country %>
Status: <%= @message.status %>
TTL: <%= @message.ttl %>
Shorten: <%= @message.shorten %>
</pre>

<%= link_to "Messages", messages_path %>